mini_lima:
  prompt_template: "mini_lima/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/home/zsq259/Desktop/1/Mini-LIMA/LLaMA-Factory/checkpoints/qwen_sft/checkpoint-2500"
    model_kwargs:
      torch_dtype: "bfloat16"
      trust_remote_code: True
    temperature: 0.7
    do_sample: True
    max_new_tokens: 2048
    top_p: 1.0
  pretty_name: "Mini Lima"